DELETE FROM activities
WHERE title IN (
    'Today Green 88',
    'Today Yellow 63',
    'Today Orange 38',
    'Today Red 13'
);

INSERT INTO activities
    (
        title,
        content,
        creator_user_id,
        author_name,
        cover_url,
        avatar_url,
        like_count,
        liked,
        start_at,
        end_at,
        tag_ids_json,
        tags_json,
        recruit_count,
        location_text,
        map_image_url,
        image_urls_json,
        invite_qr_url,
        status
    )
VALUES
    (
        'Today Green 88',
        'Today activity with plenty of time left, used to verify the green progress state.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-green/600/800',
        'https://picsum.photos/seed/meetfun-avatar-green/100/100',
        18,
        0,
        DATE_SUB(NOW(), INTERVAL 1 HOUR),
        TIMESTAMP(CURRENT_DATE, '23:30:00'),
        '[1,6]',
        '["摄影","社交"]',
        12,
        'South Bank, London SE1',
        'https://picsum.photos/seed/meetfun-map-today-green/800/360',
        '["https://picsum.photos/seed/meetfun-today-green/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-green',
        'PUBLISHED'
    ),
    (
        'Today Yellow 63',
        'Today activity with about two thirds of the time remaining, used to verify yellow.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-yellow/600/800',
        'https://picsum.photos/seed/meetfun-avatar-yellow/100/100',
        21,
        0,
        DATE_SUB(NOW(), INTERVAL 5 HOUR),
        TIMESTAMP(CURRENT_DATE, '23:30:00'),
        '[10,6]',
        '["桌游","社交"]',
        16,
        'Waterloo, London SE1',
        'https://picsum.photos/seed/meetfun-map-today-yellow/800/360',
        '["https://picsum.photos/seed/meetfun-today-yellow/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-yellow',
        'PUBLISHED'
    ),
    (
        'Today Orange 38',
        'Today activity with less than half the time remaining, used to verify orange.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-orange/600/800',
        'https://picsum.photos/seed/meetfun-avatar-orange/100/100',
        27,
        0,
        DATE_SUB(NOW(), INTERVAL 14 HOUR),
        TIMESTAMP(CURRENT_DATE, '23:30:00'),
        '[2,12]',
        '["运动","跑步"]',
        20,
        'Hyde Park Corner, London W1J',
        'https://picsum.photos/seed/meetfun-map-today-orange/800/360',
        '["https://picsum.photos/seed/meetfun-today-orange/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-orange',
        'PUBLISHED'
    ),
    (
        'Today Red 13',
        'Today activity almost finished, used to verify the red progress state.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-red/600/800',
        'https://picsum.photos/seed/meetfun-avatar-red/100/100',
        33,
        0,
        DATE_SUB(NOW(), INTERVAL 57 HOUR),
        TIMESTAMP(CURRENT_DATE, '23:30:00'),
        '[4,6]',
        '["美食","社交"]',
        10,
        'Shoreditch High Street, London E1',
        'https://picsum.photos/seed/meetfun-map-today-red/800/360',
        '["https://picsum.photos/seed/meetfun-today-red/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-red',
        'PUBLISHED'
    );
