INSERT INTO activities
    (
        title,
        content,
        creator_user_id,
        author_name,
        cover_url,
        avatar_url,
        like_count,
        liked,
        start_at,
        end_at,
        tag_ids_json,
        tags_json,
        recruit_count,
        location_text,
        map_image_url,
        image_urls_json,
        invite_qr_url,
        status
    )
VALUES
    (
        'Today Photo Walk',
        'A relaxed walk along the Thames with short photo stops and a coffee break after sunset.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-photo/600/800',
        'https://picsum.photos/seed/meetfun-avatar-1/100/100',
        8,
        0,
        DATE_ADD(NOW(), INTERVAL 2 HOUR),
        DATE_ADD(NOW(), INTERVAL 5 HOUR),
        '[1,6]',
        '["Photography","Social"]',
        12,
        'South Bank, London SE1',
        'https://picsum.photos/seed/meetfun-map-southbank/800/360',
        '["https://picsum.photos/seed/meetfun-today-photo/600/800","https://picsum.photos/seed/meetfun-today-photo-2/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-photo',
        'PUBLISHED'
    ),
    (
        'Today Board Games',
        'Bring one lightweight game or join a table when you arrive. Beginners are very welcome.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-board/600/800',
        'https://picsum.photos/seed/meetfun-avatar-2/100/100',
        15,
        0,
        DATE_ADD(NOW(), INTERVAL 3 HOUR),
        DATE_ADD(NOW(), INTERVAL 7 HOUR),
        '[10,6]',
        '["Board Games","Social"]',
        16,
        'Waterloo, London SE1',
        'https://picsum.photos/seed/meetfun-map-waterloo/800/360',
        '["https://picsum.photos/seed/meetfun-today-board/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-board',
        'PUBLISHED'
    ),
    (
        'Today Run Club',
        'A steady 5K route with warm-up and cooldown. Pace groups will be decided on arrival.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-run/600/800',
        'https://picsum.photos/seed/meetfun-avatar-3/100/100',
        21,
        0,
        DATE_ADD(NOW(), INTERVAL 4 HOUR),
        DATE_ADD(NOW(), INTERVAL 6 HOUR),
        '[2,12]',
        '["Sport","Running"]',
        20,
        'Hyde Park Corner, London W1J',
        'https://picsum.photos/seed/meetfun-map-hyde/800/360',
        '["https://picsum.photos/seed/meetfun-today-run/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-run',
        'PUBLISHED'
    ),
    (
        'Week Coffee Chat',
        'A small table meetup for newcomers and regulars to share plans, hobbies, and weekend ideas.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-week-coffee/600/800',
        'https://picsum.photos/seed/meetfun-avatar-4/100/100',
        11,
        0,
        DATE_ADD(NOW(), INTERVAL 2 DAY),
        DATE_ADD(NOW(), INTERVAL 2 DAY) + INTERVAL 3 HOUR,
        '[4,6]',
        '["Food","Social"]',
        10,
        'Shoreditch High Street, London E1',
        'https://picsum.photos/seed/meetfun-map-shoreditch/800/360',
        '["https://picsum.photos/seed/meetfun-week-coffee/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-week-coffee',
        'PUBLISHED'
    ),
    (
        'Week Museum Hour',
        'One hour in a gallery followed by casual discussion nearby. No art background needed.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-week-museum/600/800',
        'https://picsum.photos/seed/meetfun-avatar-5/100/100',
        19,
        0,
        DATE_ADD(NOW(), INTERVAL 3 DAY),
        DATE_ADD(NOW(), INTERVAL 3 DAY) + INTERVAL 4 HOUR,
        '[3,6]',
        '["Learning","Social"]',
        14,
        'Trafalgar Square, London WC2N',
        'https://picsum.photos/seed/meetfun-map-trafalgar/800/360',
        '["https://picsum.photos/seed/meetfun-week-museum/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-week-museum',
        'PUBLISHED'
    ),
    (
        'Week Live Music',
        'Meet before a local live set, then listen together and share recommendations after.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-week-music/600/800',
        'https://picsum.photos/seed/meetfun-avatar-6/100/100',
        25,
        0,
        DATE_ADD(NOW(), INTERVAL 5 DAY),
        DATE_ADD(NOW(), INTERVAL 5 DAY) + INTERVAL 5 HOUR,
        '[7,6]',
        '["Music","Social"]',
        18,
        'Camden Town, London NW1',
        'https://picsum.photos/seed/meetfun-map-camden/800/360',
        '["https://picsum.photos/seed/meetfun-week-music/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-week-music',
        'PUBLISHED'
    ),
    (
        'Month Hiking Prep',
        'Plan a gentle weekend trail, divide supplies, and match people by travel route.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-month-hike/600/800',
        'https://picsum.photos/seed/meetfun-avatar-7/100/100',
        16,
        0,
        DATE_ADD(NOW(), INTERVAL 12 DAY),
        DATE_ADD(NOW(), INTERVAL 12 DAY) + INTERVAL 4 HOUR,
        '[9,2]',
        '["Camping","Sport"]',
        15,
        'Richmond Station, London TW9',
        'https://picsum.photos/seed/meetfun-map-richmond/800/360',
        '["https://picsum.photos/seed/meetfun-month-hike/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-month-hike',
        'PUBLISHED'
    ),
    (
        'Month Food Crawl',
        'A small-group route through three food stops. Everyone votes on the final dessert place.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-month-food/600/800',
        'https://picsum.photos/seed/meetfun-avatar-8/100/100',
        28,
        0,
        DATE_ADD(NOW(), INTERVAL 18 DAY),
        DATE_ADD(NOW(), INTERVAL 18 DAY) + INTERVAL 5 HOUR,
        '[4,5]',
        '["Food","Travel"]',
        12,
        'Borough Market, London SE1',
        'https://picsum.photos/seed/meetfun-map-borough/800/360',
        '["https://picsum.photos/seed/meetfun-month-food/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-month-food',
        'PUBLISHED'
    ),
    (
        'Month Film Night',
        'Pick a film together, meet before the screening, and chat about it after.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-month-film/600/800',
        'https://picsum.photos/seed/meetfun-avatar-9/100/100',
        31,
        0,
        DATE_ADD(NOW(), INTERVAL 24 DAY),
        DATE_ADD(NOW(), INTERVAL 24 DAY) + INTERVAL 4 HOUR,
        '[11,6]',
        '["Movie","Social"]',
        20,
        'Leicester Square, London WC2H',
        'https://picsum.photos/seed/meetfun-map-leicester/800/360',
        '["https://picsum.photos/seed/meetfun-month-film/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-month-film',
        'PUBLISHED'
    );
