DELETE FROM activities
WHERE title IN (
    'Today Photo Walk',
    'Today Board Games',
    'Today Run Club',
    'Week Coffee Chat',
    'Week Museum Hour',
    'Week Live Music',
    'Month Hiking Prep',
    'Month Food Crawl',
    'Month Film Night'
);

INSERT INTO activities
    (
        title,
        content,
        creator_user_id,
        author_name,
        cover_url,
        avatar_url,
        like_count,
        liked,
        start_at,
        end_at,
        tag_ids_json,
        tags_json,
        recruit_count,
        location_text,
        map_image_url,
        image_urls_json,
        invite_qr_url,
        status
    )
VALUES
    (
        'Today Green 88',
        'Today activity with plenty of time left, used to verify the green progress state.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-green/600/800',
        'https://picsum.photos/seed/meetfun-avatar-green/100/100',
        18,
        0,
        DATE_SUB(NOW(), INTERVAL 1 HOUR),
        DATE_ADD(NOW(), INTERVAL 7 HOUR),
        '[1,6]',
        '["Photography","Social"]',
        12,
        'South Bank, London SE1',
        'https://picsum.photos/seed/meetfun-map-today-green/800/360',
        '["https://picsum.photos/seed/meetfun-today-green/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-green',
        'PUBLISHED'
    ),
    (
        'Today Yellow 63',
        'Today activity with about two thirds of the time remaining, used to verify yellow.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-yellow/600/800',
        'https://picsum.photos/seed/meetfun-avatar-yellow/100/100',
        21,
        0,
        DATE_SUB(NOW(), INTERVAL 3 HOUR),
        DATE_ADD(NOW(), INTERVAL 5 HOUR),
        '[10,6]',
        '["Board Games","Social"]',
        16,
        'Waterloo, London SE1',
        'https://picsum.photos/seed/meetfun-map-today-yellow/800/360',
        '["https://picsum.photos/seed/meetfun-today-yellow/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-yellow',
        'PUBLISHED'
    ),
    (
        'Today Orange 38',
        'Today activity with less than half the time remaining, used to verify orange.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-orange/600/800',
        'https://picsum.photos/seed/meetfun-avatar-orange/100/100',
        27,
        0,
        DATE_SUB(NOW(), INTERVAL 5 HOUR),
        DATE_ADD(NOW(), INTERVAL 3 HOUR),
        '[2,12]',
        '["Sport","Running"]',
        20,
        'Hyde Park Corner, London W1J',
        'https://picsum.photos/seed/meetfun-map-today-orange/800/360',
        '["https://picsum.photos/seed/meetfun-today-orange/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-orange',
        'PUBLISHED'
    ),
    (
        'Today Red 13',
        'Today activity almost finished, used to verify the red progress state.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-today-red/600/800',
        'https://picsum.photos/seed/meetfun-avatar-red/100/100',
        33,
        0,
        DATE_SUB(NOW(), INTERVAL 7 HOUR),
        DATE_ADD(NOW(), INTERVAL 1 HOUR),
        '[4,6]',
        '["Food","Social"]',
        10,
        'Shoreditch High Street, London E1',
        'https://picsum.photos/seed/meetfun-map-today-red/800/360',
        '["https://picsum.photos/seed/meetfun-today-red/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-today-red',
        'PUBLISHED'
    ),
    (
        'Week Green 88',
        'This week activity with plenty of time left, used to verify green outside today.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-week-green/600/800',
        'https://picsum.photos/seed/meetfun-avatar-week-green/100/100',
        13,
        0,
        DATE_SUB(NOW(), INTERVAL 12 HOUR),
        DATE_ADD(NOW(), INTERVAL 84 HOUR),
        '[3,6]',
        '["Learning","Social"]',
        14,
        'Trafalgar Square, London WC2N',
        'https://picsum.photos/seed/meetfun-map-week-green/800/360',
        '["https://picsum.photos/seed/meetfun-week-green/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-week-green',
        'PUBLISHED'
    ),
    (
        'Week Yellow 63',
        'This week activity with about two thirds remaining, used to verify yellow.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-week-yellow/600/800',
        'https://picsum.photos/seed/meetfun-avatar-week-yellow/100/100',
        17,
        0,
        DATE_SUB(NOW(), INTERVAL 2 DAY),
        DATE_ADD(NOW(), INTERVAL 80 HOUR),
        '[7,6]',
        '["Music","Social"]',
        18,
        'Camden Town, London NW1',
        'https://picsum.photos/seed/meetfun-map-week-yellow/800/360',
        '["https://picsum.photos/seed/meetfun-week-yellow/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-week-yellow',
        'PUBLISHED'
    ),
    (
        'Week Orange 38',
        'This week activity with less than half remaining, used to verify orange.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-week-orange/600/800',
        'https://picsum.photos/seed/meetfun-avatar-week-orange/100/100',
        22,
        0,
        DATE_SUB(NOW(), INTERVAL 5 DAY),
        DATE_ADD(NOW(), INTERVAL 3 DAY),
        '[9,2]',
        '["Camping","Sport"]',
        15,
        'Richmond Station, London TW9',
        'https://picsum.photos/seed/meetfun-map-week-orange/800/360',
        '["https://picsum.photos/seed/meetfun-week-orange/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-week-orange',
        'PUBLISHED'
    ),
    (
        'Week Red 13',
        'This week activity close to finishing, used to verify red outside today.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-week-red/600/800',
        'https://picsum.photos/seed/meetfun-avatar-week-red/100/100',
        24,
        0,
        DATE_SUB(NOW(), INTERVAL 7 DAY),
        DATE_ADD(NOW(), INTERVAL 1 DAY),
        '[11,6]',
        '["Movie","Social"]',
        20,
        'Leicester Square, London WC2H',
        'https://picsum.photos/seed/meetfun-map-week-red/800/360',
        '["https://picsum.photos/seed/meetfun-week-red/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-week-red',
        'PUBLISHED'
    ),
    (
        'Month Green 88',
        'This month activity with plenty of remaining time, used to verify green.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-month-green/600/800',
        'https://picsum.photos/seed/meetfun-avatar-month-green/100/100',
        14,
        0,
        DATE_SUB(NOW(), INTERVAL 2 DAY),
        DATE_ADD(NOW(), INTERVAL 14 DAY),
        '[5,6]',
        '["Travel","Social"]',
        12,
        'Borough Market, London SE1',
        'https://picsum.photos/seed/meetfun-map-month-green/800/360',
        '["https://picsum.photos/seed/meetfun-month-green/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-month-green',
        'PUBLISHED'
    ),
    (
        'Month Yellow 63',
        'This month activity with about two thirds remaining, used to verify yellow.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-month-yellow/600/800',
        'https://picsum.photos/seed/meetfun-avatar-month-yellow/100/100',
        19,
        0,
        DATE_SUB(NOW(), INTERVAL 8 DAY),
        DATE_ADD(NOW(), INTERVAL 13 DAY),
        '[1,5]',
        '["Photography","Travel"]',
        18,
        'Greenwich, London SE10',
        'https://picsum.photos/seed/meetfun-map-month-yellow/800/360',
        '["https://picsum.photos/seed/meetfun-month-yellow/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-month-yellow',
        'PUBLISHED'
    ),
    (
        'Month Orange 38',
        'This month activity with less than half remaining, used to verify orange.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-month-orange/600/800',
        'https://picsum.photos/seed/meetfun-avatar-month-orange/100/100',
        29,
        0,
        DATE_SUB(NOW(), INTERVAL 18 DAY),
        DATE_ADD(NOW(), INTERVAL 11 DAY),
        '[8,2]',
        '["Fitness","Sport"]',
        22,
        'Victoria Park, London E3',
        'https://picsum.photos/seed/meetfun-map-month-orange/800/360',
        '["https://picsum.photos/seed/meetfun-month-orange/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-month-orange',
        'PUBLISHED'
    ),
    (
        'Month Red 13',
        'This month activity close to finishing, used to verify red.',
        1,
        'MeetFun',
        'https://picsum.photos/seed/meetfun-month-red/600/800',
        'https://picsum.photos/seed/meetfun-avatar-month-red/100/100',
        36,
        0,
        DATE_SUB(NOW(), INTERVAL 20 DAY),
        DATE_ADD(NOW(), INTERVAL 10 DAY),
        '[7,11]',
        '["Music","Movie"]',
        20,
        'Hackney Central, London E8',
        'https://picsum.photos/seed/meetfun-map-month-red/800/360',
        '["https://picsum.photos/seed/meetfun-month-red/600/800"]',
        'https://api.qrserver.com/v1/create-qr-code/?size=440x440&data=meetfun-month-red',
        'PUBLISHED'
    );
